# Generated by Django 5.2.16 on 2026-07-18 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=256)),
                ('user_type', models.CharField(choices=[('applicant', 'Applicant'), ('recruiter', 'Recruiter'), ('admin', 'Admin'), ('hr', 'HR'), ('hr_manager', 'HR Manager'), ('hr_recruiter', 'HR Recruiter')], max_length=20)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('contact', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('profile', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='domain.account')),
                ('impersonated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='domain.account')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(blank=True, default='', max_length=20)),
                ('street_address', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('pincode', models.CharField(blank=True, default='', max_length=12)),
                ('gst_number', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('industry_type', models.CharField(blank=True, default='', max_length=100)),
                ('number_of_employees', models.CharField(blank=True, default='', max_length=50)),
                ('website', models.URLField(blank=True, default='')),
                ('profile_pic', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company', to='domain.account')),
            ],
            options={
                'verbose_name_plural': 'company profiles',
            },
        ),
        migrations.CreateModel(
            name='CustomListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(choices=[('jobTitles', 'Job titles'), ('qualifications', 'Qualifications')], max_length=30)),
                ('value', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'custom list entries',
                'constraints': [models.UniqueConstraint(fields=('list_name', 'value'), name='unique_list_value')],
            },
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending approval'), ('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='pending', max_length=10)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('salary', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('job_type', models.CharField(blank=True, default='', max_length=50)),
                ('qualification', models.CharField(blank=True, default='', max_length=255)),
                ('experience', models.CharField(blank=True, default='', max_length=100)),
                ('gender', models.CharField(blank=True, default='Any', max_length=20)),
                ('number_of_openings', models.CharField(blank=True, default='', max_length=10)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('hiring_process', models.JSONField(blank=True, default=list)),
                ('active_until', models.DateField(blank=True, null=True)),
                ('seed_priority', models.IntegerField(default=0)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='domain.companyprofile')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_posted', to='domain.account')),
            ],
            options={
                'ordering': ['-seed_priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected'), ('Hired', 'Hired')], default='Applied', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='domain.account')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='domain.jobpost')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('job', 'applicant'), name='unique_job_applicant')],
            },
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to='domain.account')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='domain.jobpost')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('account', 'job'), name='unique_saved_job')],
            },
        ),
    ]
