# Generated by Django 5.2.16 on 2026-07-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.IntegerField(default=0)),
                ('data', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_client_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('user_client_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'ordering': ['order_index'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.IntegerField(default=0)),
                ('data', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.CharField(blank=True, db_index=True, default='', max_length=254)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['order_index'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.IntegerField(default=0)),
                ('data', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'ordering': ['order_index'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KeyValueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.JSONField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'key-value entries',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.IntegerField(default=0)),
                ('data', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('user_type', models.CharField(blank=True, default='', max_length=64)),
                ('email', models.CharField(blank=True, db_index=True, default='', max_length=254)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'user',
                'ordering': ['order_index'],
                'abstract': False,
            },
        ),
    ]
